version: '3'

networks:
    kaiyuanshe:

services:
    kys-service:
        image: kaiyuanshe/kys-service
        environment:
            - NODE_ENV=production
            - PORT=8080
        ports:
            - 8080:8080
        networks:
            - kaiyuanshe
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
    caddy:
        depends_on:
            - kys-service
        image: caddy
        ports:
            - 80:80
            - 443:443
        networks:
            - kaiyuanshe
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
        command: caddy reverse-proxy --from service.kaiyuanshe.cn --to kys-service:8080
