version: '3'

networks:
    kaiyuanshe:

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${APP_SECRET}
        volumes:
            - ./data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - kaiyuanshe
        restart: always
    kys-service:
        depends_on:
            - postgres
        image: kaiyuanshe/kys-service
        environment:
            - DATABASE_URL=postgres://postgres:${APP_SECRET}@postgres:5432/postgres
            - NODE_ENV=production
            - PORT=8080
        ports:
            - 8080:8080
        networks:
            - kaiyuanshe
        restart: always
