# reference:
#   1. https://github.com/docker/build-push-action/blob/master/docs/advanced/push-multi-registries.md
#   2. https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md

name: Deploy to Production environment
on:
    push:
        tags:
            - v*
env:
    ARTIFACT_PATH: /tmp/artifact.tar
    BOX_NAME: kys-service
    BOX_URL: kaiyuanshe/kys-service

jobs:
    push_to_registries:
        name: Save Docker image to GitHub artifact
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v3

            - name: Inject Environment variables
              run: |
                  cat > .env <<EOF
                  ${{ secrets.ENV_FILE }}
                  EOF
            - uses: docker/setup-qemu-action@v2
            - uses: docker/setup-buildx-action@v2

            - name: Build Image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64
                  tags: ${{ env.BOX_URL }}:latest
                  outputs: type=docker,dest=${{ env.ARTIFACT_PATH }}

            - name: Pick Docker Compose
              run: mv ./docker-compose.yml /tmp

            - name: Save Image
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ env.BOX_NAME }}
                  path: |
                      ${{ env.ARTIFACT_PATH }}
                      /tmp/docker-compose.yml
    pull_to_run:
        name: Pull Docker image to run
        needs: push_to_registries
        runs-on: ubuntu-latest
        steps:
            - name: Fetch Image
              uses: actions/download-artifact@v3
              with:
                  name: ${{ env.BOX_NAME }}

            - name: Transport Image
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: ./
                  remote: /tmp
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  privateKey: ${{ secrets.SSH_KEY }}

            - name: Run Image
              uses: garygrossgarten/github-action-ssh@release
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  privateKey: ${{ secrets.SSH_KEY }}
                  command: |
                      sudo docker load < ${{ env.ARTIFACT_PATH }}
                      sudo docker image ls -a
                      cd /tmp
                      sudo docker compose down
                      sudo docker compose up -d
                      sudo docker image prune -a -f
